services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    env_file: ./.env
    environment:
      POSTGRES_PASSWORD: '${DATABASE_PASSWORD}'
      POSTGRES_USER: '${DATABASE_USER}'
      POSTGRES_NAME: '${DATABASE_NAME}'
      POSTGRES_HOST: '${DATABASE_HOST}'
      POSTGRES_PORT: '${DATABASE_PORT}'
    volumes:
      - ./.docker-volumes/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      app:
        ipv4_address: 10.19.0.2
  app:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - ${PORT}:${PORT}
    env_file: ./.env
    environment:
      - PORT=${PORT}
    restart: unless-stopped
    networks:
      app:
        ipv4_address: 10.19.0.3

networks:
  app:
    name: optitech-api
    driver: bridge
    ipam:
      config:
        - subnet: 10.19.0.0/16
          gateway: 10.19.0.1
