// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCreateInstitutionService implements pgx.CopyFromSource.
type iteratorForCreateInstitutionService struct {
	rows                 []CreateInstitutionServiceParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateInstitutionService) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateInstitutionService) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].InstitutionID,
		r.rows[0].ServiceID,
		r.rows[0].CreatedAt,
	}, nil
}

func (r iteratorForCreateInstitutionService) Err() error {
	return nil
}

func (q *Queries) CreateInstitutionService(ctx context.Context, arg []CreateInstitutionServiceParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"institution_services"}, []string{"institution_id", "service_id", "created_at"}, &iteratorForCreateInstitutionService{rows: arg})
}
