// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: directory_institution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDirectoryInstitution = `-- name: CreateDirectoryInstitution :one
INSERT INTO directory_institution(institution_id, directory_id, created_at)
VALUES ($1, $2, $3)
RETURNING directory_institution_id, institution_id, directory_id, created_at, updated_at, deleted_at
`

type CreateDirectoryInstitutionParams struct {
	InstitutionID int32            `json:"institution_id"`
	DirectoryID   int32            `json:"directory_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateDirectoryInstitution(ctx context.Context, arg CreateDirectoryInstitutionParams) (DirectoryInstitution, error) {
	row := q.db.QueryRow(ctx, createDirectoryInstitution, arg.InstitutionID, arg.DirectoryID, arg.CreatedAt)
	var i DirectoryInstitution
	err := row.Scan(
		&i.DirectoryInstitutionID,
		&i.InstitutionID,
		&i.DirectoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAllDirectoryInstitutions = `-- name: DeleteAllDirectoryInstitutions :execresult
UPDATE directory_institution
SET deleted_at = $1
WHERE deleted_at IS NULL
`

func (q *Queries) DeleteAllDirectoryInstitutions(ctx context.Context, deletedAt pgtype.Timestamp) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAllDirectoryInstitutions, deletedAt)
}

const deleteDirectoryInstitutionById = `-- name: DeleteDirectoryInstitutionById :exec
UPDATE directory_institution
SET deleted_at = $2
WHERE directory_institution_id = $1
`

type DeleteDirectoryInstitutionByIdParams struct {
	DirectoryInstitutionID int32            `json:"directory_institution_id"`
	DeletedAt              pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) DeleteDirectoryInstitutionById(ctx context.Context, arg DeleteDirectoryInstitutionByIdParams) error {
	_, err := q.db.Exec(ctx, deleteDirectoryInstitutionById, arg.DirectoryInstitutionID, arg.DeletedAt)
	return err
}

const getDirectoryInstitution = `-- name: GetDirectoryInstitution :one
SELECT directory_institution_id, institution_id, directory_id, created_at, updated_at, deleted_at FROM directory_institution
WHERE directory_institution_id = $1 LIMIT 1
`

func (q *Queries) GetDirectoryInstitution(ctx context.Context, directoryInstitutionID int32) (DirectoryInstitution, error) {
	row := q.db.QueryRow(ctx, getDirectoryInstitution, directoryInstitutionID)
	var i DirectoryInstitution
	err := row.Scan(
		&i.DirectoryInstitutionID,
		&i.InstitutionID,
		&i.DirectoryID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDirectoryInstitutionByDirectoryId = `-- name: GetDirectoryInstitutionByDirectoryId :many
SELECT d.directory_id, d.parent_id, d.name, d.created_at, d.updated_at, d.deleted_at, i.institution_id, i.asesor_id, i.institution_name, i.logo, i.description, i.created_at, i.updated_at, i.deleted_at, di.directory_institution_id, di.institution_id, di.directory_id, di.created_at, di.updated_at, di.deleted_at
FROM directory_institution di
JOIN directory_tree d ON di.directory_id = d.directory_id
JOIN institution i ON di.institution_id = d.institution_id 
WHERE di.directory_id = $1
`

type GetDirectoryInstitutionByDirectoryIdRow struct {
	DirectoryTree        DirectoryTree        `json:"directory_tree"`
	Institution          Institution          `json:"institution"`
	DirectoryInstitution DirectoryInstitution `json:"directory_institution"`
}

func (q *Queries) GetDirectoryInstitutionByDirectoryId(ctx context.Context, directoryID int32) ([]GetDirectoryInstitutionByDirectoryIdRow, error) {
	rows, err := q.db.Query(ctx, getDirectoryInstitutionByDirectoryId, directoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDirectoryInstitutionByDirectoryIdRow
	for rows.Next() {
		var i GetDirectoryInstitutionByDirectoryIdRow
		if err := rows.Scan(
			&i.DirectoryTree.DirectoryID,
			&i.DirectoryTree.ParentID,
			&i.DirectoryTree.Name,
			&i.DirectoryTree.CreatedAt,
			&i.DirectoryTree.UpdatedAt,
			&i.DirectoryTree.DeletedAt,
			&i.Institution.InstitutionID,
			&i.Institution.AsesorID,
			&i.Institution.InstitutionName,
			&i.Institution.Logo,
			&i.Institution.Description,
			&i.Institution.CreatedAt,
			&i.Institution.UpdatedAt,
			&i.Institution.DeletedAt,
			&i.DirectoryInstitution.DirectoryInstitutionID,
			&i.DirectoryInstitution.InstitutionID,
			&i.DirectoryInstitution.DirectoryID,
			&i.DirectoryInstitution.CreatedAt,
			&i.DirectoryInstitution.UpdatedAt,
			&i.DirectoryInstitution.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirectoryInstitutionByName = `-- name: GetDirectoryInstitutionByName :one
SELECT institution_id, directory_id
FROM directory_institution
WHERE directory_institution_id = $1
`

type GetDirectoryInstitutionByNameRow struct {
	InstitutionID int32 `json:"institution_id"`
	DirectoryID   int32 `json:"directory_id"`
}

func (q *Queries) GetDirectoryInstitutionByName(ctx context.Context, directoryInstitutionID int32) (GetDirectoryInstitutionByNameRow, error) {
	row := q.db.QueryRow(ctx, getDirectoryInstitutionByName, directoryInstitutionID)
	var i GetDirectoryInstitutionByNameRow
	err := row.Scan(&i.InstitutionID, &i.DirectoryID)
	return i, err
}

const listDirectoryInstitutions = `-- name: ListDirectoryInstitutions :many
SELECT directory_institution_id, institution_id, directory_id, created_at, updated_at, deleted_at FROM directory_institution
ORDER BY directory_institution_id
`

func (q *Queries) ListDirectoryInstitutions(ctx context.Context) ([]DirectoryInstitution, error) {
	rows, err := q.db.Query(ctx, listDirectoryInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DirectoryInstitution
	for rows.Next() {
		var i DirectoryInstitution
		if err := rows.Scan(
			&i.DirectoryInstitutionID,
			&i.InstitutionID,
			&i.DirectoryID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
