// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: institution_services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

type CreateInstitutionServiceParams struct {
	InstitutionID int32            `json:"institution_id"`
	ServiceID     int32            `json:"service_id"`
	CreatedAt     pgtype.Timestamp `json:"created_at"`
}

const deleteAllInstitutionServices = `-- name: DeleteAllInstitutionServices :execresult
UPDATE institution_services
SET deleted_at = $1
WHERE deleted_at IS NULL
`

func (q *Queries) DeleteAllInstitutionServices(ctx context.Context, deletedAt pgtype.Timestamp) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAllInstitutionServices, deletedAt)
}

const listInstitutionServices = `-- name: ListInstitutionServices :many
SELECT services.service_name ,services.service_id FROM institution_services
INNER JOIN services ON  institution_services.services_id=services.service_id
WHERE institution_services.institution_id= $1
ORDER BY services.service_id
`

type ListInstitutionServicesRow struct {
	ServiceName string `json:"service_name"`
	ServiceID   int64  `json:"service_id"`
}

func (q *Queries) ListInstitutionServices(ctx context.Context, institutionID int32) ([]ListInstitutionServicesRow, error) {
	rows, err := q.db.Query(ctx, listInstitutionServices, institutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstitutionServicesRow
	for rows.Next() {
		var i ListInstitutionServicesRow
		if err := rows.Scan(&i.ServiceName, &i.ServiceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
