// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: institution.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInstitution = `-- name: CreateInstitution :one
INSERT INTO institution (institution_name , description, created_at,asesor_id)
VALUES ($1, $2, $3, $4)
RETURNING institution.institution_id
`

type CreateInstitutionParams struct {
	InstitutionName string           `json:"institution_name"`
	Description     string           `json:"description"`
	CreatedAt       pgtype.Timestamp `json:"created_at"`
	AsesorID        pgtype.Int4      `json:"asesor_id"`
}

func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (int32, error) {
	row := q.db.QueryRow(ctx, createInstitution,
		arg.InstitutionName,
		arg.Description,
		arg.CreatedAt,
		arg.AsesorID,
	)
	var institution_id int32
	err := row.Scan(&institution_id)
	return institution_id, err
}

const deleteAllInstitutions = `-- name: DeleteAllInstitutions :exec
UPDATE institution
set deleted_at = $1
where deleted_at is NULL
`

func (q *Queries) DeleteAllInstitutions(ctx context.Context, deletedAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteAllInstitutions, deletedAt)
	return err
}

const deleteInstitution = `-- name: DeleteInstitution :exec
UPDATE institution
SET deleted_at = $2
WHERE institution_id = $1 AND deleted_at IS NULL
`

type DeleteInstitutionParams struct {
	InstitutionID int32            `json:"institution_id"`
	DeletedAt     pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) DeleteInstitution(ctx context.Context, arg DeleteInstitutionParams) error {
	_, err := q.db.Exec(ctx, deleteInstitution, arg.InstitutionID, arg.DeletedAt)
	return err
}

const getInstitution = `-- name: GetInstitution :one
SELECT institution_id, asesor_id, institution_name, logo, description, created_at, updated_at, deleted_at FROM institution
WHERE institution_id = $1
AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetInstitution(ctx context.Context, institutionID int32) (Institution, error) {
	row := q.db.QueryRow(ctx, getInstitution, institutionID)
	var i Institution
	err := row.Scan(
		&i.InstitutionID,
		&i.AsesorID,
		&i.InstitutionName,
		&i.Logo,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getInstitutionByClient = `-- name: GetInstitutionByClient :one
SELECT  i.institution_id FROM institution i
INNER JOIN institution_client ON i.institution_id=institution_client.institution_id
WHERE  institution_client.client_id= $1
AND i.deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetInstitutionByClient(ctx context.Context, clientID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getInstitutionByClient, clientID)
	var institution_id int32
	err := row.Scan(&institution_id)
	return institution_id, err
}

const getInstitutionByName = `-- name: GetInstitutionByName :one
SELECT  institution_name, logo, description
FROM institution
WHERE institution_name = $1
`

type GetInstitutionByNameRow struct {
	InstitutionName string      `json:"institution_name"`
	Logo            pgtype.Text `json:"logo"`
	Description     string      `json:"description"`
}

func (q *Queries) GetInstitutionByName(ctx context.Context, institutionName string) (GetInstitutionByNameRow, error) {
	row := q.db.QueryRow(ctx, getInstitutionByName, institutionName)
	var i GetInstitutionByNameRow
	err := row.Scan(&i.InstitutionName, &i.Logo, &i.Description)
	return i, err
}

const listInstitutions = `-- name: ListInstitutions :many
SELECT institution_id, asesor_id, institution_name, logo, description, created_at, updated_at, deleted_at FROM institution
WHERE deleted_at IS NULL
ORDER BY institution_name
`

func (q *Queries) ListInstitutions(ctx context.Context) ([]Institution, error) {
	rows, err := q.db.Query(ctx, listInstitutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Institution
	for rows.Next() {
		var i Institution
		if err := rows.Scan(
			&i.InstitutionID,
			&i.AsesorID,
			&i.InstitutionName,
			&i.Logo,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAsesorInstitution = `-- name: UpdateAsesorInstitution :exec
UPDATE institution
SET asesor_id= $2 ,updated_at=$3
WHERE institution_id = $1
`

type UpdateAsesorInstitutionParams struct {
	InstitutionID int32            `json:"institution_id"`
	AsesorID      pgtype.Int4      `json:"asesor_id"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateAsesorInstitution(ctx context.Context, arg UpdateAsesorInstitutionParams) error {
	_, err := q.db.Exec(ctx, updateAsesorInstitution, arg.InstitutionID, arg.AsesorID, arg.UpdatedAt)
	return err
}

const updateInstitution = `-- name: UpdateInstitution :exec
UPDATE institution
SET institution_name = $2, description = $3,  updated_at=$4,asesor_id= $5
WHERE institution_id = $1
`

type UpdateInstitutionParams struct {
	InstitutionID   int32            `json:"institution_id"`
	InstitutionName string           `json:"institution_name"`
	Description     string           `json:"description"`
	UpdatedAt       pgtype.Timestamp `json:"updated_at"`
	AsesorID        pgtype.Int4      `json:"asesor_id"`
}

func (q *Queries) UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) error {
	_, err := q.db.Exec(ctx, updateInstitution,
		arg.InstitutionID,
		arg.InstitutionName,
		arg.Description,
		arg.UpdatedAt,
		arg.AsesorID,
	)
	return err
}

const updateLogoInstitution = `-- name: UpdateLogoInstitution :exec
UPDATE institution
SET logo = $2 ,updated_at=$3 WHERE institution_id = $1
`

type UpdateLogoInstitutionParams struct {
	InstitutionID int32            `json:"institution_id"`
	Logo          pgtype.Text      `json:"logo"`
	UpdatedAt     pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateLogoInstitution(ctx context.Context, arg UpdateLogoInstitutionParams) error {
	_, err := q.db.Exec(ctx, updateLogoInstitution, arg.InstitutionID, arg.Logo, arg.UpdatedAt)
	return err
}
