// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
	"time"
)

type Asesor struct {
	AsesorID int64        `json:"asesor_id"`
	Username string       `json:"username"`
	Photo    string       `json:"photo"`
	About    string       `json:"about"`
	CreateAt time.Time    `json:"create_at"`
	UpdateAt sql.NullTime `json:"update_at"`
}

type Client struct {
	ClientID      int64         `json:"client_id"`
	GivenName     string        `json:"given_name"`
	Surname       string        `json:"surname"`
	Email         string        `json:"email"`
	Password      string        `json:"password"`
	AsesorID      sql.NullInt32 `json:"asesor_id"`
	InstitutionID sql.NullInt32 `json:"institution_id"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
}

type Institution struct {
	InstitutionID   int64          `json:"institution_id"`
	AsesorID        sql.NullInt32  `json:"asesor_id"`
	InstitutionName string         `json:"institution_name"`
	Logo            sql.NullString `json:"logo"`
	Description     string         `json:"description"`
	Services        []string       `json:"services"`
	CreateAt        time.Time      `json:"create_at"`
	UpdateAt        sql.NullTime   `json:"update_at"`
}
