// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: services.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createServices = `-- name: CreateServices :one
INSERT INTO services(name, created_at)
VALUES ($1, $2)
RETURNING services_id, name, created_at, updated_at, deleted_at
`

type CreateServicesParams struct {
	Name      string           `json:"name"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateServices(ctx context.Context, arg CreateServicesParams) (Service, error) {
	row := q.db.QueryRow(ctx, createServices, arg.Name, arg.CreatedAt)
	var i Service
	err := row.Scan(
		&i.ServicesID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAllServicess = `-- name: DeleteAllServicess :execresult
UPDATE services
SET deleted_at = $1
WHERE deleted_at IS NULL
`

func (q *Queries) DeleteAllServicess(ctx context.Context, deletedAt pgtype.Timestamp) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteAllServicess, deletedAt)
}

const deleteServicesById = `-- name: DeleteServicesById :exec
UPDATE services
SET deleted_at = $2
WHERE services_id = $1
`

type DeleteServicesByIdParams struct {
	ServicesID int64            `json:"services_id"`
	DeletedAt  pgtype.Timestamp `json:"deleted_at"`
}

func (q *Queries) DeleteServicesById(ctx context.Context, arg DeleteServicesByIdParams) error {
	_, err := q.db.Exec(ctx, deleteServicesById, arg.ServicesID, arg.DeletedAt)
	return err
}

const getServices = `-- name: GetServices :one
SELECT services_id, name, created_at, updated_at, deleted_at FROM services
WHERE services_id = $1 LIMIT 1
`

func (q *Queries) GetServices(ctx context.Context, servicesID int64) (Service, error) {
	row := q.db.QueryRow(ctx, getServices, servicesID)
	var i Service
	err := row.Scan(
		&i.ServicesID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServicesByName = `-- name: GetServicesByName :one
SELECT name
FROM services
WHERE services_id = $1
`

func (q *Queries) GetServicesByName(ctx context.Context, servicesID int64) (string, error) {
	row := q.db.QueryRow(ctx, getServicesByName, servicesID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listServicess = `-- name: ListServicess :many
SELECT services_id, name, created_at, updated_at, deleted_at FROM services
ORDER BY services_id
`

func (q *Queries) ListServicess(ctx context.Context) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicess)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ServicesID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateServicesById = `-- name: UpdateServicesById :exec
UPDATE services
SET name = $2, updated_at = $3
WHERE services_id = $1
`

type UpdateServicesByIdParams struct {
	ServicesID int64            `json:"services_id"`
	Name       string           `json:"name"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

func (q *Queries) UpdateServicesById(ctx context.Context, arg UpdateServicesByIdParams) error {
	_, err := q.db.Exec(ctx, updateServicesById, arg.ServicesID, arg.Name, arg.UpdatedAt)
	return err
}
